### ISSUE TITLE
Support typing_extensions and 3.8 types

### ISSUE THREAD

**Issue by flying-sheep** [agronholm/sphinx-autodoc-typehints#108]
3.8 introduced

- TypedDict (used by being subclassed, no support here necessary)
- Protocol (dito)
- Final (simple marker generic like `Type`)
- Literal ([PEP 586](https://www.python.org/dev/peps/pep-0586/), Like `Union`, but for values)

Only `Literal` deserves special attention, as its values need to be rendered like ```', '.join(f'``{v!r}``' for v in literal.__args__)``` (easy enough), and because it needs normalization with `Union`: `Union[Literal['a', None], int]` is equivalent to `Union[Literal['a'], None, int]`, and `Union[Literal['a'], Literal['b']]` is equivalent to `Literal['a', 'b']`.

---

Since few people have 3.8, it would be cool to support backport patterns like

```py
try:
    from typing import Literal
except Exception:
    from typing_extensions import Literal
```

To properly support this, I think we simply need to extend `if annotation_cls.__module__ == 'typing'`. Since we set `module = 'typing'` in that branch, the links should work, even when the annotation comes from `typing_extensions`.

**Comment by agronholm** [comment]
Have you checked the master branch lately? `Literal` support was added a few months ago, and two hours ago I added `TypeDict` support as well.

What manner of support do you envision for `Final` and `Protocol` in typeguard?

I will not support `typing_extensions` because they are made in such a way that detecting them is damn near impossible. If they give up their hostile stance against run time type checking then I will reconsider.

**Comment by flying-sheep** [comment]
> What manner of support do you envision for `Final` and `Protocol` in typeguard?

This is `sphinx_autodoc_typehints`, not `typeguard`. As said above, I excluded `Final` and `Protocol` from the request, as their subclasses can simply be displayed by name like any other class.

> Have you checked the master branch lately? Literal support was added a few months ago, and two hours ago I added TypeDict support as well.

I guess you thought this was the `typeguard` repo, which might well support it. This one doesn’t.

> I will not support `typing_extensions` because they are made in such a way that detecting them is damn near impossible.

As also said above, I think that we just need to change `if annotation_cls.__module__ == 'typing'` to `if annotation_cls.__module__ in {'typing', 'typing_extensions'}`. Do you think that’s not sufficient? Why?

**Comment by flying-sheep** [comment]
```py
$ ipython
Python 3.7.4 (default, Oct  4 2019, 06:57:26) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.8.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: from typing_extensions import Literal

In [2]: Literal[1].__origin__                                                                                                                                             
Out[2]: typing_extensions.Literal
```

**Comment by agronholm** [comment]
With the latest version of typing_extensions (3.7.4):
```
Python 3.6.9 (default, Jul  3 2019, 15:08:07) 
[GCC 9.1.1 20190503 (Red Hat 9.1.1-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from typing_extensions import Literal
>>> Literal[1].__origin__
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: '_Literal' object has no attribute '__origin__'
```

**Comment by agronholm** [comment]
I even tried all the other released versions and I didn't get it to work with **any** of them.

**Comment by agronholm** [comment]
On further testing, it **does** work on Python 3.7, but not 3.6 or 3.5.

**Comment by agronholm** [comment]
I'm also not convinced that sphinx-autodoc-typehints needs to alter the rendering of `Literal`, particularly when it's part of a larger typing construct.

**Comment by flying-sheep** [comment]
> On further testing, it does work on Python 3.7, but not 3.6 or 3.5.

Ah! That explains it. They basically retain the code for every Python version and use that code to implement on top of it. And since things changed fast in past `typing` versions, this is the result. So yeah. If we get an `__origin__`, and its `__module__` is  'typing_extensions', we should get into the typing branch.

> I'm also not convinced that sphinx-autodoc-typehints needs to alter the rendering of Literal, particularly when it's part of a larger typing construct.

What do you mean? the Unification? I just think it’d look neater

What I’m very convinced about is that it should render its values using `repr`.

`Literal['a']` should be rendered as `Literal['a']`, not `Literal[a]`. There is no `a`, `'a'` is a string literal!

**Comment by agronholm** [comment]
> What I’m very convinced about is that it should render its values using repr: Literal['a'] should be rendered as Literal['a'], not Literal[a]. There is no variable called a in play here, only a string literal 'a'!

`Literal` renders the single quotes either way, and sphinx-autodoc-typehints does not have a special processing code path for it, so I wonder what goes wrong then.

**Comment by agronholm** [comment]
Riiiight, because it **doesn't** have a special code path. Thus it's treated like a forward reference, thus the lack of single quotes.

**Comment by agronholm** [comment]
This I will fix, but I am not convinced about the other parts of the request.

**Comment by flying-sheep** [comment]
I mean, #109 is literally all that’s needed to fix the “support typing_extensions” part for Python 3.7 (and as you said, on 3.6, it’s too hard anyway)

**Comment by agronholm** [comment]
I've now implemented support for typing_extensions and Literal. I have not done any normalization changes, as I'm not sure we should be doing that. Is this satisfactory?

**Comment by flying-sheep** [comment]
Yes, thank you!
