### ISSUE TITLE
Does not work on 3.7.0b1

### ISSUE THREAD

**Issue by Fuyukai** [agronholm/sphinx-autodoc-typehints#33]
```
Configuration error:
There is a programable error in your configuration file:

Traceback (most recent call last):
  File "/home/laura/.local/share/virtualenvs/curious-yiBjxk2Q/lib/python3.7/site-packages/sphinx/config.py", line 161, in __init__
    execfile_(filename, config)
  File "/home/laura/.local/share/virtualenvs/curious-yiBjxk2Q/lib/python3.7/site-packages/sphinx/util/pycompat.py", line 150, in execfile_
    exec_(code, _globals)
  File "conf.py", line 55, in <module>
    import sphinx_autodoc_typehints
  File "/home/laura/.local/share/virtualenvs/curious-yiBjxk2Q/lib/python3.7/site-packages/sphinx_autodoc_typehints.py", line 2, in <module>
    from typing import get_type_hints, TypeVar, Any, AnyStr, GenericMeta
ImportError: cannot import name 'GenericMeta' from 'typing' (/usr/lib64/python3.7/typing.py)

make: *** [Makefile:20: html] Error 2
```

No mention of GenericMeta being removed in the 3.7 changelog.

**Comment by agronholm** [comment]
GenericMeta was also never documented in previous versions, so the devs were fully within their rights to yank it out. Now I just have to figure out a way to replace the functionality.

**Comment by agronholm** [comment]
Sigh...this is a lot more complicated with 3.7 in play now. Just checking against Generic does not solve the issue.
