### ISSUE TITLE
List does not works in Python 3.5.2

### ISSUE THREAD

**Issue by fukatani** [agronholm/sphinx-autodoc-typehints#113]
https://travis-ci.org/kmyk/online-judge-tools/builds/603136293?utm_source=github_status&utm_medium=notification

In Python 3.6, `make -c docs` was passed.

But Python 3.5.2, `make -c docs` was failed.
```
Exception occurred:
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/sphinx_autodoc_typehints.py", line 98, in format_annotation
    if params and annotation is not getattr(sys.modules[module], class_name):
AttributeError: module 'typing' has no attribute 'List<~T>'
The full traceback has been saved in /tmp/sphinx-err-hvw9liug.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
Makefile:20: recipe for target 'html' failed
make: *** [html] Error 2
make: Leaving directory '/home/travis/build/kmyk/online-judge-tools/docs'
The command "make -C docs html" exited with 2.
183.73s
```

Is this bug or as designed?

**Comment by fukatani** [comment]
I attach full traceback.

```
# Sphinx version: 2.2.0
# Python version: 3.5.2 (CPython)
# Docutils version: 0.14 
# Jinja2 version: 2.9.6
# Last messages:
#   ソースを読み込み中...[ 19%] modules
#   
#   ソースを読み込み中...[ 23%] onlinejudge
#   
#   ソースを読み込み中...[ 28%] onlinejudge.dispatch
#   
#   ソースを読み込み中...[ 33%] onlinejudge.service
#   
#   ソースを読み込み中...[ 38%] onlinejudge.service.anarchygolf
#   
# Loaded extensions:
#   sphinx.ext.doctest (2.2.0) from /home/ryo/workspace/github/chainer-wind-env/lib/python3.5/site-packages/sphinx/ext/doctest.py
#   alabaster (0.7.10) from /home/ryo/workspace/github/chainer-wind-env/lib/python3.5/site-packages/alabaster/__init__.py
#   sphinxcontrib.devhelp (1.0.1) from /home/ryo/workspace/github/chainer-wind-env/lib/python3.5/site-packages/sphinxcontrib/devhelp/__init__.py
#   sphinxcontrib.htmlhelp (1.0.2) from /home/ryo/workspace/github/chainer-wind-env/lib/python3.5/site-packages/sphinxcontrib/htmlhelp/__init__.py
#   sphinxcontrib.applehelp (1.0.1) from /home/ryo/workspace/github/chainer-wind-env/lib/python3.5/site-packages/sphinxcontrib/applehelp/__init__.py
#   sphinxcontrib.qthelp (1.0.2) from /home/ryo/workspace/github/chainer-wind-env/lib/python3.5/site-packages/sphinxcontrib/qthelp/__init__.py
#   sphinx.ext.intersphinx (2.2.0) from /home/ryo/workspace/github/chainer-wind-env/lib/python3.5/site-packages/sphinx/ext/intersphinx.py
#   sphinx.ext.mathjax (2.2.0) from /home/ryo/workspace/github/chainer-wind-env/lib/python3.5/site-packages/sphinx/ext/mathjax.py
#   sphinx.ext.autodoc (2.2.0) from /home/ryo/workspace/github/chainer-wind-env/lib/python3.5/site-packages/sphinx/ext/autodoc/__init__.py
#   sphinx_autodoc_typehints (unknown version) from /home/ryo/workspace/github/chainer-wind-env/lib/python3.5/site-packages/sphinx_autodoc_typehints.py
#   sphinxcontrib.serializinghtml (1.1.3) from /home/ryo/workspace/github/chainer-wind-env/lib/python3.5/site-packages/sphinxcontrib/serializinghtml/__init__.py
#   sphinx.ext.todo (2.2.0) from /home/ryo/workspace/github/chainer-wind-env/lib/python3.5/site-packages/sphinx/ext/todo.py
#   sphinx.ext.viewcode (2.2.0) from /home/ryo/workspace/github/chainer-wind-env/lib/python3.5/site-packages/sphinx/ext/viewcode.py
Traceback (most recent call last):
  File "/home/ryo/workspace/github/chainer-wind-env/lib/python3.5/site-packages/sphinx/cmd/build.py", line 276, in build_main
    app.build(args.force_all, filenames)
  File "/home/ryo/workspace/github/chainer-wind-env/lib/python3.5/site-packages/sphinx/application.py", line 346, in build
    self.builder.build_update()
  File "/home/ryo/workspace/github/chainer-wind-env/lib/python3.5/site-packages/sphinx/builders/__init__.py", line 299, in build_update
    len(to_build))
  File "/home/ryo/workspace/github/chainer-wind-env/lib/python3.5/site-packages/sphinx/builders/__init__.py", line 311, in build
    updated_docnames = set(self.read())
  File "/home/ryo/workspace/github/chainer-wind-env/lib/python3.5/site-packages/sphinx/builders/__init__.py", line 418, in read
    self._read_serial(docnames)
  File "/home/ryo/workspace/github/chainer-wind-env/lib/python3.5/site-packages/sphinx/builders/__init__.py", line 439, in _read_serial
    self.read_doc(docname)
  File "/home/ryo/workspace/github/chainer-wind-env/lib/python3.5/site-packages/sphinx/builders/__init__.py", line 479, in read_doc
    doctree = read_doc(self.app, self.env, self.env.doc2path(docname))
  File "/home/ryo/workspace/github/chainer-wind-env/lib/python3.5/site-packages/sphinx/io.py", line 326, in read_doc
    pub.publish()
  File "/home/ryo/workspace/github/chainer-wind-env/lib/python3.5/site-packages/docutils/core.py", line 217, in publish
    self.settings)
  File "/home/ryo/workspace/github/chainer-wind-env/lib/python3.5/site-packages/sphinx/io.py", line 114, in read
    self.parse()
  File "/home/ryo/workspace/github/chainer-wind-env/lib/python3.5/site-packages/docutils/readers/__init__.py", line 78, in parse
    self.parser.parse(self.input, document)
  File "/home/ryo/workspace/github/chainer-wind-env/lib/python3.5/site-packages/sphinx/parsers.py", line 95, in parse
    self.statemachine.run(inputlines, document, inliner=self.inliner)
  File "/home/ryo/workspace/github/chainer-wind-env/lib/python3.5/site-packages/docutils/parsers/rst/states.py", line 171, in run
    input_source=document['source'])
  File "/home/ryo/workspace/github/chainer-wind-env/lib/python3.5/site-packages/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File "/home/ryo/workspace/github/chainer-wind-env/lib/python3.5/site-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/home/ryo/workspace/github/chainer-wind-env/lib/python3.5/site-packages/docutils/parsers/rst/states.py", line 2753, in underline
    self.section(title, source, style, lineno - 1, messages)
  File "/home/ryo/workspace/github/chainer-wind-env/lib/python3.5/site-packages/docutils/parsers/rst/states.py", line 327, in section
    self.new_subsection(title, lineno, messages)
  File "/home/ryo/workspace/github/chainer-wind-env/lib/python3.5/site-packages/docutils/parsers/rst/states.py", line 395, in new_subsection
    node=section_node, match_titles=True)
  File "/home/ryo/workspace/github/chainer-wind-env/lib/python3.5/site-packages/docutils/parsers/rst/states.py", line 282, in nested_parse
    node=node, match_titles=match_titles)
  File "/home/ryo/workspace/github/chainer-wind-env/lib/python3.5/site-packages/docutils/parsers/rst/states.py", line 196, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/home/ryo/workspace/github/chainer-wind-env/lib/python3.5/site-packages/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File "/home/ryo/workspace/github/chainer-wind-env/lib/python3.5/site-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/home/ryo/workspace/github/chainer-wind-env/lib/python3.5/site-packages/docutils/parsers/rst/states.py", line 2326, in explicit_markup
    nodelist, blank_finish = self.explicit_construct(match)
  File "/home/ryo/workspace/github/chainer-wind-env/lib/python3.5/site-packages/docutils/parsers/rst/states.py", line 2338, in explicit_construct
    return method(self, expmatch)
  File "/home/ryo/workspace/github/chainer-wind-env/lib/python3.5/site-packages/docutils/parsers/rst/states.py", line 2081, in directive
    directive_class, match, type_name, option_presets)
  File "/home/ryo/workspace/github/chainer-wind-env/lib/python3.5/site-packages/docutils/parsers/rst/states.py", line 2130, in run_directive
    result = directive_instance.run()
  File "/home/ryo/workspace/github/chainer-wind-env/lib/python3.5/site-packages/sphinx/ext/autodoc/directive.py", line 146, in run
    documenter.generate(more_content=self.content)
  File "/home/ryo/workspace/github/chainer-wind-env/lib/python3.5/site-packages/sphinx/ext/autodoc/__init__.py", line 732, in generate
    self.document_members(all_members)
  File "/home/ryo/workspace/github/chainer-wind-env/lib/python3.5/site-packages/sphinx/ext/autodoc/__init__.py", line 654, in document_members
    check_module=members_check_module and not isattr)
  File "/home/ryo/workspace/github/chainer-wind-env/lib/python3.5/site-packages/sphinx/ext/autodoc/__init__.py", line 1188, in generate
    all_members=all_members)
  File "/home/ryo/workspace/github/chainer-wind-env/lib/python3.5/site-packages/sphinx/ext/autodoc/__init__.py", line 732, in generate
    self.document_members(all_members)
  File "/home/ryo/workspace/github/chainer-wind-env/lib/python3.5/site-packages/sphinx/ext/autodoc/__init__.py", line 1177, in document_members
    super().document_members(all_members)
  File "/home/ryo/workspace/github/chainer-wind-env/lib/python3.5/site-packages/sphinx/ext/autodoc/__init__.py", line 654, in document_members
    check_module=members_check_module and not isattr)
  File "/home/ryo/workspace/github/chainer-wind-env/lib/python3.5/site-packages/sphinx/ext/autodoc/__init__.py", line 729, in generate
    self.add_content(more_content)
  File "/home/ryo/workspace/github/chainer-wind-env/lib/python3.5/site-packages/sphinx/ext/autodoc/__init__.py", line 471, in add_content
    for i, line in enumerate(self.process_doc(docstrings)):
  File "/home/ryo/workspace/github/chainer-wind-env/lib/python3.5/site-packages/sphinx/ext/autodoc/__init__.py", line 441, in process_doc
    self.options, docstringlines)
  File "/home/ryo/workspace/github/chainer-wind-env/lib/python3.5/site-packages/sphinx/application.py", line 450, in emit
    return self.events.emit(event, *args)
  File "/home/ryo/workspace/github/chainer-wind-env/lib/python3.5/site-packages/sphinx/events.py", line 103, in emit
    results.append(callback(self.app, *args))
  File "/home/ryo/workspace/github/chainer-wind-env/lib/python3.5/site-packages/sphinx_autodoc_typehints.py", line 387, in process_docstring
    type_hints['return'], fully_qualified=app.config.typehints_fully_qualified)
  File "/home/ryo/workspace/github/chainer-wind-env/lib/python3.5/site-packages/sphinx_autodoc_typehints.py", line 98, in format_annotation
    if params and annotation is not getattr(sys.modules[module], class_name):
AttributeError: module 'typing' has no attribute 'List<~T>'
```

**Comment by agronholm** [comment]
It's not the only thing that breaks on 3.5.2. I've added a Travis test job to catch these in the future, but for now you can either downgrade sphinx-autodoc-typehints or upgrade your Python into something more recent.

**Comment by dylmye** [comment]
Getting a similar issue here:

```
Exception occurred:
  File "C:\Python\3.8\lib\site-packages\sphinx_autodoc_typehints.py", line 98, in format_annotation
    if params and annotation is not getattr(sys.modules[module], class_name):
AttributeError: module 'typing' has no attribute 'IO'>'
```

<details><summary>Full Traceback</summary>
<p>
```
# Sphinx version: 2.2.1
# Python version: 3.8.0 (CPython)
# Docutils version: 0.15.2 release
# Jinja2 version: 2.10.3
# Last messages:
#   loading intersphinx inventory from https://docs.python.org/objects.inv...
#   intersphinx inventory has moved: https://docs.python.org/objects.inv -> https://docs.python.org/3/objects.inv
#   building [mo]: targets for 0 po files that are out of date
#   building [html]: targets for 3 source files that are out of date
#   updating environment:
#   [new config]
#   3 added, 0 changed, 0 removed
#   reading sources... [ 33%] getting-started
#   reading sources... [ 66%] index
#   reading sources... [100%] phial
# Loaded extensions:
#   sphinx.ext.mathjax (2.2.1) from C:\Python\3.8\lib\site-packages\sphinx\ext\mathjax.py
#   sphinxcontrib.applehelp (1.0.1) from C:\Python\3.8\lib\site-packages\sphinxcontrib\applehelp\__init__.py
#   sphinxcontrib.devhelp (1.0.1) from C:\Python\3.8\lib\site-packages\sphinxcontrib\devhelp\__init__.py
#   sphinxcontrib.htmlhelp (1.0.2) from C:\Python\3.8\lib\site-packages\sphinxcontrib\htmlhelp\__init__.py
#   sphinxcontrib.serializinghtml (1.1.3) from C:\Python\3.8\lib\site-packages\sphinxcontrib\serializinghtml\__init__.py
#   sphinxcontrib.qthelp (1.0.2) from C:\Python\3.8\lib\site-packages\sphinxcontrib\qthelp\__init__.py
#   alabaster (0.7.12) from C:\Python\3.8\lib\site-packages\alabaster\__init__.py
#   sphinx.ext.autodoc (2.2.1) from C:\Python\3.8\lib\site-packages\sphinx\ext\autodoc\__init__.py
#   sphinx_autodoc_typehints (unknown version) from C:\Python\3.8\lib\site-packages\sphinx_autodoc_typehints.py
#   sphinx.ext.intersphinx (2.2.1) from C:\Python\3.8\lib\site-packages\sphinx\ext\intersphinx.py
#   sphinx.ext.coverage (2.2.1) from C:\Python\3.8\lib\site-packages\sphinx\ext\coverage.py
#   sphinx.ext.viewcode (2.2.1) from C:\Python\3.8\lib\site-packages\sphinx\ext\viewcode.py
Traceback (most recent call last):
  File "C:\Python\3.8\lib\site-packages\sphinx\cmd\build.py", line 276, in build_main
    app.build(args.force_all, filenames)
  File "C:\Python\3.8\lib\site-packages\sphinx\application.py", line 346, in build
    self.builder.build_update()
  File "C:\Python\3.8\lib\site-packages\sphinx\builders\__init__.py", line 297, in build_update
    self.build(to_build,
  File "C:\Python\3.8\lib\site-packages\sphinx\builders\__init__.py", line 311, in build
    updated_docnames = set(self.read())
  File "C:\Python\3.8\lib\site-packages\sphinx\builders\__init__.py", line 418, in read
    self._read_serial(docnames)
  File "C:\Python\3.8\lib\site-packages\sphinx\builders\__init__.py", line 439, in _read_serial
    self.read_doc(docname)
  File "C:\Python\3.8\lib\site-packages\sphinx\builders\__init__.py", line 479, in read_doc
    doctree = read_doc(self.app, self.env, self.env.doc2path(docname))
  File "C:\Python\3.8\lib\site-packages\sphinx\io.py", line 326, in read_doc
    pub.publish()
  File "C:\Python\3.8\lib\site-packages\docutils\core.py", line 216, in publish
    self.document = self.reader.read(self.source, self.parser,
  File "C:\Python\3.8\lib\site-packages\sphinx\io.py", line 114, in read
    self.parse()
  File "C:\Python\3.8\lib\site-packages\docutils\readers\__init__.py", line 77, in parse
    self.parser.parse(self.input, document)
  File "C:\Python\3.8\lib\site-packages\sphinx\parsers.py", line 95, in parse
    self.statemachine.run(inputlines, document, inliner=self.inliner)
  File "C:\Python\3.8\lib\site-packages\docutils\parsers\rst\states.py", line 170, in run
    results = StateMachineWS.run(self, input_lines, input_offset,
  File "C:\Python\3.8\lib\site-packages\docutils\statemachine.py", line 238, in run
    context, next_state, result = self.check_line(
  File "C:\Python\3.8\lib\site-packages\docutils\statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "C:\Python\3.8\lib\site-packages\docutils\parsers\rst\states.py", line 2771, in underline
    self.section(title, source, style, lineno - 1, messages)
  File "C:\Python\3.8\lib\site-packages\docutils\parsers\rst\states.py", line 327, in section
    self.new_subsection(title, lineno, messages)
  File "C:\Python\3.8\lib\site-packages\docutils\parsers\rst\states.py", line 393, in new_subsection
    newabsoffset = self.nested_parse(
  File "C:\Python\3.8\lib\site-packages\docutils\parsers\rst\states.py", line 281, in nested_parse
    state_machine.run(block, input_offset, memo=self.memo,
  File "C:\Python\3.8\lib\site-packages\docutils\parsers\rst\states.py", line 196, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "C:\Python\3.8\lib\site-packages\docutils\statemachine.py", line 238, in run
    context, next_state, result = self.check_line(
  File "C:\Python\3.8\lib\site-packages\docutils\statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "C:\Python\3.8\lib\site-packages\docutils\parsers\rst\states.py", line 2771, in underline
    self.section(title, source, style, lineno - 1, messages)
  File "C:\Python\3.8\lib\site-packages\docutils\parsers\rst\states.py", line 327, in section
    self.new_subsection(title, lineno, messages)
  File "C:\Python\3.8\lib\site-packages\docutils\parsers\rst\states.py", line 393, in new_subsection
    newabsoffset = self.nested_parse(
  File "C:\Python\3.8\lib\site-packages\docutils\parsers\rst\states.py", line 281, in nested_parse
    state_machine.run(block, input_offset, memo=self.memo,
  File "C:\Python\3.8\lib\site-packages\docutils\parsers\rst\states.py", line 196, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "C:\Python\3.8\lib\site-packages\docutils\statemachine.py", line 238, in run
    context, next_state, result = self.check_line(
  File "C:\Python\3.8\lib\site-packages\docutils\statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "C:\Python\3.8\lib\site-packages\docutils\parsers\rst\states.py", line 2344, in explicit_markup
    nodelist, blank_finish = self.explicit_construct(match)
  File "C:\Python\3.8\lib\site-packages\docutils\parsers\rst\states.py", line 2356, in explicit_construct
    return method(self, expmatch)
  File "C:\Python\3.8\lib\site-packages\docutils\parsers\rst\states.py", line 2098, in directive
    return self.run_directive(
  File "C:\Python\3.8\lib\site-packages\docutils\parsers\rst\states.py", line 2148, in run_directive
    result = directive_instance.run()
  File "C:\Python\3.8\lib\site-packages\sphinx\ext\autodoc\directive.py", line 146, in run
    documenter.generate(more_content=self.content)
  File "C:\Python\3.8\lib\site-packages\sphinx\ext\autodoc\__init__.py", line 732, in generate
    self.document_members(all_members)
  File "C:\Python\3.8\lib\site-packages\sphinx\ext\autodoc\__init__.py", line 652, in document_members
    documenter.generate(
  File "C:\Python\3.8\lib\site-packages\sphinx\ext\autodoc\__init__.py", line 1186, in generate
    return super().generate(more_content=more_content,
  File "C:\Python\3.8\lib\site-packages\sphinx\ext\autodoc\__init__.py", line 729, in generate
    self.add_content(more_content)
  File "C:\Python\3.8\lib\site-packages\sphinx\ext\autodoc\__init__.py", line 1172, in add_content
    super().add_content(more_content)
  File "C:\Python\3.8\lib\site-packages\sphinx\ext\autodoc\__init__.py", line 471, in add_content
    for i, line in enumerate(self.process_doc(docstrings)):
  File "C:\Python\3.8\lib\site-packages\sphinx\ext\autodoc\__init__.py", line 439, in process_doc
    self.env.app.emit('autodoc-process-docstring',
  File "C:\Python\3.8\lib\site-packages\sphinx\application.py", line 450, in emit
    return self.events.emit(event, *args)
  File "C:\Python\3.8\lib\site-packages\sphinx\events.py", line 103, in emit
    results.append(callback(self.app, *args))
  File "C:\Python\3.8\lib\site-packages\sphinx_autodoc_typehints.py", line 364, in process_docstring
    formatted_annotation = format_annotation(
  File "C:\Python\3.8\lib\site-packages\sphinx_autodoc_typehints.py", line 98, in format_annotation
    if params and annotation is not getattr(sys.modules[module], class_name):
AttributeError: module 'typing' has no attribute 'IO'>'

```
</p>
</details>

**Comment by agronholm** [comment]
@dylmye Please file a separate issue. The test suite passes on 3.8 (unlike on 3.5.2) so a new test has to be added to cover this use case.

**Comment by dylmye** [comment]
Sure thing. I'm getting this issue on 3.7.x too, I'll make sure to mention that.

**Comment by agronholm** [comment]
I think you can remove the pin to 1.8.0 now. I've rewritten the annotation formatting logic and the tests pass on Python 3.5.2 as well as 3.8.

**Comment by fukatani** [comment]
Sure, Thanks!
